# Generated by Django 3.2.9 on 2022-03-19 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_created', models.DateTimeField(auto_now_add=True)),
                ('transfer_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to='banks.customers')),
                ('transfer_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sender', to='banks.customers')),
            ],
        ),
    ]
